### ISSUE TITLE
[haxe.org] Replace Flash to AIR

### ISSUE THREAD

**Issue by VladimirCores** [HaxeFoundation/haxe.org-comments#62]
Just want to ask you to replace Flash to AIR (together with logo), since Flash is no longer supported by Adobe, and only Harman AIR currently exists (which of course utilize Flash libraries inside), and usually people distrust to this word - Flash. Thanks.

**Comment by nanjizal** [comment]
Perhaps a mash up of these logos something 'artist' with a humours side, since humour and art are expressions so not legally as tricky.
![nme96](https://user-images.githubusercontent.com/20134338/83683780-d5b53700-a5dd-11ea-95a4-a544e2416667.png)
 +
![oldFlash](https://user-images.githubusercontent.com/20134338/83682984-963a1b00-a5dc-11ea-84e0-c570300a421a.png)
+
![OZEWoKKu_400x400](https://user-images.githubusercontent.com/20134338/83683353-2aa47d80-a5dd-11ea-92ee-65ed8f276cc2.png)

Animate / Old Flash versions still publish Flash that you run locally or with the app, and OpenFL / NME allows embedding of assets, AIR is just one way to use them.

Harman have not provided financial support to Haxe community as far as I am aware? Harman's involvement in AIR does not seem to have yet involved any serious marketing, I am not sure anyone is particularly sure of their motives, atleast we knew with Adobe that they were chasing js with Harman no one knows - they may well be courting Flutter and certainly Haxe community should be promoting using swf's with OpenFL or NME not AIR.

The AIR format is just a zipped up SWF a ZippedSwf, I do not see Harman as relevant going forward unless they put some effort to really help communities Haxe and Actionscripers communities, on the as3 discord most users are moving to Haxe or Flutter, no one is trusting AIR.

While Haxe supports the SWF format I see no reason to promote Adobe or Harman that's why the macromedia old logo seems ideal anyone who understands the poweful aspects of flash will no doubt still remember it, but have no idea what the Harman logo looks like, it's much more important we focus ex flash users coming to Haxe on OpenFL and NME, where code is evolving and companies are investing resources.

**Comment by VladimirCores** [comment]
No more questions. Thanks for answer @nanjizal : )

**Comment by nanjizal** [comment]
Was not official answer just my viewpoint, if you need any help with integrating with any of the Haxe toolkits do get in contact, there lots of us that know flash well and have used the various haxe toolkits.
